import mockjs from 'mockjs';
import { getRule, postRule } from './mock/rule';
import { getActivities, getNotice, getFakeList } from './mock/api';
import { getFakeChartData } from './mock/chart';
import { getProfileBasicData } from './mock/profile';
import { getProfileAdvancedData } from './mock/profile';
import { getNotices } from './mock/notices';
import { format, delay } from 'roadhog-api-doc';

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

const json = {
	"userInfo": {
		"id": 1217,
		"udesk_id": "",
		"user_group_id": 0,
		"user_name": "shenck",
		"organization_id": 111,
		"position_id": 7,
		"enable_status": 1,
		"job_status": 1,
		"job_change_type": 1,
		"name": "沈晨凯",
		"employee_number": "JY100000",
		"gender": 0,
		"age": 0,
		"phone": "13222222222",
		"email": "shenck@joyowo.com",
		"entry_time": 1458748800,
		"report_user_id": 1,
		"is_update_password": 1,
		"is_sales_manager": 0,
		"create_user": "guyx",
		"create_time": 1508829543,
		"update_time": 0,
		"delete_time": 0,
		"is_delete": 0,
		"remark": "",
		"team_id": 0,
		"userName": "shenck"
	},
	"errorCode": 0,
	"userRole": [{
		"id": 1.0,
		"name": "权限控制",
		"code": "power_control",
		"displayName": "权限控制",
		"type": 1.0,
		"url": "",
		"relaction_url": "",
		"system_url": "https://testadmin.joyomm.com",
		"system_code": "PHPACCOUNT",
		"parentId": 0.0,
		"children": [{
			"id": 2.0,
			"name": "用户管理",
			"code": "user",
			"displayName": "用户管理",
			"type": 1.0,
			"url": "/privilege/user",
			"relaction_url": "/privilege/user/index,/privilege/user/add,/privilege/user/edit,/privilege/user/enable,/privilege/user/",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPACCOUNT",
			"parentId": 1.0
		}, {
			"id": 3.0,
			"name": "用户组管理",
			"code": "usergroup",
			"displayName": "用户组管理",
			"type": 1.0,
			"url": "/privilege/usergroup",
			"relaction_url": "/privilege/usergroup/add,/privilege/usergroup/index",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPACCOUNT",
			"parentId": 1.0
		}, {
			"id": 4.0,
			"name": "角色管理",
			"code": "role",
			"displayName": "角色管理",
			"type": 1.0,
			"url": "/privilege/role",
			"relaction_url": "/privilege/role/index,/privilege/role/addoredit,/privilege/role/getroleinfo",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPACCOUNT",
			"parentId": 1.0
		}, {
			"id": 6.0,
			"name": "资源管理",
			"code": "resource",
			"displayName": "资源管理",
			"type": 1.0,
			"url": "/privilege/resource",
			"relaction_url": "/privilege/resource/add",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPACCOUNT",
			"parentId": 1.0
		}, {
			"id": 7.0,
			"name": "日志管理",
			"code": "log",
			"displayName": "日志管理",
			"type": 1.0,
			"url": "/privilege/log",
			"relaction_url": "/privilege/log/index,/info",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPACCOUNT",
			"parentId": 1.0
		}, {
			"id": 38.0,
			"name": "组织架构",
			"code": "privilege_organization",
			"displayName": "组织架构",
			"type": 1.0,
			"url": "/privilege/organization/index",
			"relaction_url": "",
			"system_url": "https://testadmin.joyomm.com",
			"system_code": "PHPADMIN",
			"parentId": 1.0
		}, {
			"id": 125.0,
			"name": "登录日志",
			"code": "TIANWU_LOGIN_INFO",
			"displayName": "登录日志",
			"type": 1.0,
			"url": "/permission/logininfolog",
			"system_url": "http://tigert.joyomm.com/admin",
			"system_code": "TIANWU",
			"parentId": 1.0
		}, {
			"id": 160.0,
			"name": "用户反馈",
			"code": "TIANWU_feedback_index",
			"displayName": "用户反馈",
			"type": 1.0,
			"url": "/feedback/index",
			"system_url": "http://tigert.joyomm.com/admin",
			"system_code": "TIANWU",
			"parentId": 1.0
		}, {
			"id": 379.0,
			"name": "更新客户资料",
			"code": "TIANWU_QXKZ_button_update_customer_data",
			"displayName": "更新客户资料",
			"type": 2.0,
			"system_url": "",
			"system_code": "",
			"parentId": 1.0
		}]
	}, {
		"id": 12.0,
		"name": "官网内容管理",
		"code": "content_manager",
		"displayName": "官网内容管理",
		"type": 1.0,
		"url": "",
		"relaction_url": "",
		"system_url": "https://testadmin.joyomm.com/cmsbackend",
		"system_code": "PHPCMS",
		"parentId": 0.0,
		"children": [{
			"id": 13.0,
			"name": "广告位管理",
			"code": "adv_position",
			"displayName": "广告位管理",
			"type": 1.0,
			"url": "/cms/advposition/index",
			"relaction_url": "/cms/advposition/add,/cms/advposition/edit",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 14.0,
			"name": "友情链接管理",
			"code": "friend_link",
			"displayName": "友情链接管理",
			"type": 1.0,
			"url": "/cms/friendlink/index",
			"relaction_url": "/cms/friendlink/add,/cms/friendlink/edit",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 15.0,
			"name": "友情链接分类管理",
			"code": "friend_link_cat",
			"displayName": "友情链接分类管理",
			"type": 1.0,
			"url": "/cms/friendlinkcat/index",
			"relaction_url": "",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 16.0,
			"name": "文章管理",
			"code": "article",
			"displayName": "文章管理",
			"type": 1.0,
			"url": "/cms/article",
			"relaction_url": "/cms/article/save,/cms/article/collected",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 17.0,
			"name": "文章栏目",
			"code": "articlecat",
			"displayName": "文章栏目",
			"type": 1.0,
			"url": "/cms/articlecat",
			"relaction_url": "/cms/articlecat/save,/cms/articlecat/update",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 20.0,
			"name": "内链管理",
			"code": "inner_link",
			"displayName": "内链管理",
			"type": 1.0,
			"url": "/cms/innerlink",
			"relaction_url": "",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 226.0,
			"name": "标签管理",
			"code": "articletag",
			"displayName": "标签管理",
			"type": 1.0,
			"url": "/cms/articletag/index",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 12.0
		}, {
			"id": 513.0,
			"name": "活动管理",
			"code": "TIANWU_WEB_ACTIVITY",
			"displayName": " 工作台_市场人员_活动管理",
			"type": 1.0,
			"url": "/newadmin/web/activitymanergment",
			"system_url": "http://tigert.joyomm.com/admin",
			"system_code": "TIANWU",
			"parentId": 12.0,
			"children": [{
				"id": 514.0,
				"name": "新增活动",
				"code": "TIANWU_WEB_ACTIVITY_ADD",
				"displayName": "新增活动",
				"type": 2.0,
				"url": "/newadmin/web/activitymanergment/add",
				"system_url": "http://tigert.joyomm.com/admin",
				"system_code": "TIANWU",
				"parentId": 513.0
			}, {
				"id": 516.0,
				"name": "活动管理员权限",
				"code": "TIANWU_WEB_ACTIVITY_MANAGE",
				"displayName": "活动管理员权限",
				"type": 2.0,
				"system_code": "TIANWU",
				"parentId": 513.0
			}, {
				"id": 526.0,
				"name": "编辑活动",
				"code": "TIANWU_WEB_ACTIVITY_EDITOR",
				"displayName": "编辑活动",
				"type": 2.0,
				"url": "/newadmin/web/activitymanergment/editor",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/admin",
				"system_code": "TIANWU",
				"parentId": 513.0
			}, {
				"id": 527.0,
				"name": "查看活动",
				"code": "TIANWU_WEB_ACTIVITY_CHECK",
				"displayName": "查看活动",
				"type": 2.0,
				"url": "/newadmin/web/activitymanergment/check",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/admin",
				"system_code": "TIANWU",
				"parentId": 513.0
			}]
		}]
	}, {
		"id": 205.0,
		"name": "站点管理",
		"code": "site_manager",
		"displayName": "站点管理",
		"type": 1.0,
		"url": "/cms/site/index",
		"relaction_url": "/cms/site/add,/cms/site/edit",
		"system_url": "https://testadmin.joyomm.com/cmsbackend",
		"system_code": "PHPCMS",
		"parentId": 0.0,
		"children": [{
			"id": 206.0,
			"name": "站点信息",
			"code": "SITE_INFO",
			"displayName": "站点信息",
			"type": 1.0,
			"url": "/cms/site/index",
			"relaction_url": "/cms/site/add,/cms/site/edit",
			"system_url": "https://testadmin.joyomm.com/cmsbackend",
			"system_code": "PHPCMS",
			"parentId": 205.0
		}]
	}, {
		"id": 26.0,
		"name": "无忧保管理",
		"code": "wyb",
		"displayName": "无忧保管理",
		"type": 1.0,
		"system_code": "WYB",
		"parentId": 0.0,
		"children": [{
			"id": 376.0,
			"name": "服务商管理",
			"code": "WYB_serviceManage",
			"displayName": "服务商管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 318.0,
				"name": "服务商管理",
				"code": "WYB_serviceProvider",
				"displayName": "服务商管理",
				"type": 1.0,
				"url": "/jsp/react/serviceManage/serviceProvider/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 320.0,
				"name": "服务商政策管理",
				"code": "WYB_policy",
				"displayName": "服务商政策管理",
				"type": 1.0,
				"url": "/jsp/react/serviceManage/policy/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 343.0,
				"name": "服务商详情",
				"code": "WYB_serviceProvider_detail",
				"displayName": "服务商详情",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/serviceProvider/detail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 344.0,
				"name": "新建服务商",
				"code": "WYB_serviceProvider_create",
				"displayName": "新建服务商",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/serviceProvider/create",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 345.0,
				"name": "设置政策包第一步",
				"code": "WYB_policy_step1",
				"displayName": "设置政策包第一步",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/policy/step1",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 346.0,
				"name": "设置政策包第二步",
				"code": "WYB_policy_step2",
				"displayName": "设置政策包第二步",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/policy/step2",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 347.0,
				"name": "设置政策包第三步",
				"code": "WYB_policy_step3",
				"displayName": "设置政策包第三步",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/policy/step3",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 348.0,
				"name": "设置政策包第四步",
				"code": "WYB_policy_step4",
				"displayName": "设置政策包第四步",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/policy/step4",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}, {
				"id": 349.0,
				"name": "政策包详情",
				"code": "WYB_policy_detail",
				"displayName": "政策包详情",
				"type": 2.0,
				"url": "/jsp/react/serviceManage/policy/detail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 376.0
			}]
		}, {
			"id": 321.0,
			"name": "参保城市管理",
			"code": "WYB_cityset",
			"displayName": "参保城市管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 319.0,
				"name": "城市基础设置",
				"code": "WYB_cityBase",
				"displayName": "城市基础设置",
				"type": 1.0,
				"url": "/jsp/react/cityset/cityBase/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 321.0
			}, {
				"id": 354.0,
				"name": "城市上下架编辑",
				"code": "WYB_city_jurisdiction_update",
				"displayName": "城市上下架编辑",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 321.0
			}, {
				"id": 355.0,
				"name": "城市上下架下架",
				"code": "WYB_city_jurisdiction_disable",
				"displayName": "城市上下架下架",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 321.0
			}, {
				"id": 356.0,
				"name": "城市上下架新增",
				"code": "WYB_city_jurisdiction_add",
				"displayName": "城市上下架新增",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 321.0
			}, {
				"id": 322.0,
				"name": "城市上下架管理",
				"code": "WYB_city",
				"displayName": "城市上下架管理",
				"type": 1.0,
				"url": "/jsp/react/cityset/city/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 321.0
			}]
		}, {
			"id": 66.0,
			"name": "客户管理",
			"code": "WYB_customer",
			"displayName": "无忧保客户管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 68.0,
				"name": "潜在客户-旧",
				"code": "WYB_potential2",
				"displayName": "潜在客户管理",
				"type": 1.0,
				"url": "/jsp/customer/potential",
				"relaction_url": "/jsp/customer/potentialdetail,/jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 340.0,
				"name": "潜在客户导出",
				"code": "WYB_button_export",
				"displayName": "潜在客户导出",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 361.0,
				"name": "个体户认证详情",
				"code": "WYB_individual_detail",
				"displayName": "个体户认证详情",
				"type": 2.0,
				"url": "/jsp/react/customer/individual/detail",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 370.0,
				"name": "有效客户导出",
				"code": "wyb_effective_export",
				"displayName": "有效客户导出",
				"type": 2.0,
				"url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 375.0,
				"name": "客户详情",
				"code": "WYB_valid_detail",
				"displayName": "客户详情",
				"type": 2.0,
				"url": "/jsp/react/customer/valid/detail",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 377.0,
				"name": "客户详情",
				"code": "WYB_potential_detail",
				"displayName": "潜在客户详情",
				"type": 2.0,
				"url": "/jsp/react/customer/potential/detail",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 569.0,
				"name": "潜在客户",
				"code": "WYB_potential",
				"displayName": "潜在客户管理",
				"type": 1.0,
				"url": "/jsp/react/customer/potential/index",
				"relaction_url": " ",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 540.0,
				"name": "有效客户",
				"code": "WYB_valid",
				"displayName": "有效客户管理",
				"type": 1.0,
				"url": "/jsp/react/customer/valid/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 360.0,
				"name": "个体户认证",
				"code": "WYB_individual",
				"displayName": "个体户认证",
				"type": 1.0,
				"url": "/jsp/react/customer/individual/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 374.0,
				"name": "渠道来源设置",
				"code": "WYB_channelSource",
				"displayName": "渠道来源设置",
				"type": 1.0,
				"url": "/jsp/react/customer/channelSource/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 100.0,
				"name": "个体工商户认证",
				"code": "person_s",
				"displayName": "个体工商户认证",
				"type": 1.0,
				"url": "/admin/account/personbusiness",
				"system_url": "http://test.joyomm.com",
				"system_code": "OLD_PHPADMIN",
				"parentId": 66.0
			}, {
				"id": 413.0,
				"name": "黑名单管理",
				"code": "WYB_blacklist",
				"displayName": "黑名单管理",
				"type": 1.0,
				"url": "/jsp/react/customer/blacklist/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 414.0,
				"name": "黑名单修改",
				"code": "WYB_blacklist_jurisdiction",
				"displayName": "黑名单修改",
				"type": 2.0,
				"url": "",
				"relaction_url": "",
				"system_url": "",
				"system_code": "WYB",
				"parentId": 66.0
			}, {
				"id": 459.0,
				"name": "修改手机号",
				"code": "WYB_customer_modify_mobile",
				"displayName": "修改手机号",
				"type": 2.0,
				"url": " ",
				"relaction_url": " ",
				"system_url": " ",
				"system_code": "WYB",
				"parentId": 66.0
			}]
		}, {
			"id": 70.0,
			"name": "参保人管理",
			"code": "WYB_insuracer",
			"displayName": "参保人管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 380.0,
				"name": "服务中的参保人",
				"code": "WYB_insurceServicing",
				"displayName": "服务中的参保人",
				"type": 1.0,
				"url": "/jsp/react/insuracer/insurceServicing/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 539.0,
				"name": "导入社保公积金账号",
				"code": "WYB_socialFundAccount_lead",
				"displayName": "导入社保公积金账号",
				"type": 2.0,
				"url": "/jsp/react/insuracer/socialFundAccount/lead",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 566.0,
				"name": "导入社保公积金账号",
				"code": "WYB_socialFundAccountToLead",
				"displayName": "导入社保公积金账号",
				"type": 2.0,
				"url": "/jsp/react/insuracer/socialFundAccountToLead/lead",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 381.0,
				"name": "服务终止的参保人",
				"code": "WYB_insurceServiced",
				"displayName": "服务终止的参保人",
				"type": 1.0,
				"url": "/jsp/react/insuracer/insurceServiced/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 547.0,
				"name": "社保公积金账号",
				"code": "WYB_socialFundAccount",
				"displayName": "社保公积金账号",
				"type": 1.0,
				"url": "/jsp/react/insuracer/socialFundAccount/index",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 554.0,
				"name": "社保公积金账号-操作权限",
				"code": "WYB_socialFundAccount_operation",
				"displayName": "社保公积金账号-操作权限",
				"type": 2.0,
				"url": "",
				"relaction_url": "",
				"system_url": "",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 570.0,
				"name": "参保人详情页-提前停保权限",
				"code": "WYB_insurceDetail_stopProtect",
				"displayName": "参保人详情页-提前停保权限",
				"type": 2.0,
				"url": " ",
				"relaction_url": " ",
				"system_url": " ",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 571.0,
				"name": "参保人详情页-修改参保类型权限",
				"code": "WYB_insurceDetail_modifyInsuredType",
				"displayName": "参保人详情页-修改参保类型权限",
				"type": 2.0,
				"url": " ",
				"relaction_url": " ",
				"system_url": " ",
				"system_code": "WYB",
				"parentId": 70.0
			}, {
				"id": 572.0,
				"name": "参保人详情页-发送材料权限",
				"code": "WYB_insurceDetail_sendMaterial",
				"displayName": "参保人详情页-发送材料权限",
				"type": 2.0,
				"url": " ",
				"relaction_url": " ",
				"system_url": " ",
				"system_code": "WYB",
				"parentId": 70.0
			}]
		}, {
			"id": 87.0,
			"name": "订单管理",
			"code": "WYB_order",
			"displayName": "订单管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 371.0,
				"name": "订单导出",
				"code": "wyb_order_export",
				"displayName": "订单导出",
				"type": 2.0,
				"url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 87.0
			}, {
				"id": 421.0,
				"name": "交易成功订单",
				"code": "WYB_finalizedOrder",
				"displayName": "交易成功订单",
				"type": 1.0,
				"url": "/jsp/react/order/finalizedOrder/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 87.0
			}, {
				"id": 89.0,
				"name": "未完成订单",
				"code": "WYB_wwc",
				"displayName": "未完成订单",
				"type": 1.0,
				"url": "/jsp/order/orderunfinishe",
				"relaction_url": "/jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 87.0
			}, {
				"id": 422.0,
				"name": "未完成订单-新",
				"code": "WYB_unfilledOrder",
				"displayName": "未完成订单-新",
				"type": 1.0,
				"url": "/jsp/react/order/unfilledOrder/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 87.0
			}]
		}, {
			"id": 83.0,
			"name": "退款管理",
			"code": "WYB_refund",
			"displayName": "退款管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 227.0,
				"name": "退保退款",
				"code": "WYB_refundmanage",
				"displayName": "退保退款",
				"type": 1.0,
				"url": "/jsp/refund/refundmanage",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 83.0
			}, {
				"id": 228.0,
				"name": "其他退款(旧)",
				"code": "WYB_otherrefundmanagejiu",
				"displayName": "其他退款(旧)",
				"type": 2.0,
				"url": "/jsp/refund/otherrefundmanage",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 83.0
			}, {
				"id": 229.0,
				"name": "批量退款",
				"code": "WYB_allrequest",
				"displayName": "批量退款",
				"type": 1.0,
				"url": "/jsp/request/allrequest",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 83.0
			}, {
				"id": 417.0,
				"name": "其他退款",
				"code": "WYB_otherrefundmanage",
				"displayName": "其他退款",
				"type": 1.0,
				"url": "/jsp/react/refund/otherrefundmanage/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 83.0
			}, {
				"id": 420.0,
				"name": "新增服务费退款权限",
				"code": "WYB_otherrefundmanage_create",
				"displayName": "新增服务费退款权限",
				"type": 2.0,
				"url": " ",
				"system_code": "WYB",
				"parentId": 83.0
			}]
		}, {
			"id": 391.0,
			"name": "账单管理",
			"code": "WYB_bill",
			"displayName": "账单管理",
			"type": 1.0,
			"url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 159.0,
				"name": "月账单管理",
				"code": "WYB_billMonth",
				"displayName": "月账单管理",
				"type": 1.0,
				"url": "/jsp/customer/monthbillmanage",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 391.0
			}, {
				"id": 392.0,
				"name": "服务商月账单",
				"code": "WYB_serviceBillMonth",
				"displayName": "服务商月账单",
				"type": 1.0,
				"url": "/jsp/react/bill/serviceBillMonth/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 391.0
			}, {
				"id": 555.0,
				"name": "账单导入",
				"code": "WYB_billImport",
				"displayName": "账单导入",
				"type": 1.0,
				"url": "/jsp/react/bill/billImport/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 391.0
			}]
		}, {
			"id": 75.0,
			"name": "派单管理",
			"code": "WYB_sendform",
			"displayName": "派单管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 126.0,
				"name": "待处理",
				"code": "WYB_processing",
				"displayName": "待处理",
				"type": 1.0,
				"url": "/jsp/sendorders/processing",
				"relaction_url": "/jsp/sendorders/processing.jsp",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 76.0,
				"name": "待派单",
				"code": "WYB_sendorders",
				"displayName": "待派单单据",
				"type": 1.0,
				"url": "/jsp/sendorders/stayorder",
				"relaction_url": "/jsp/sendorders/stayorderdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 351.0,
				"name": "修改参保方案",
				"code": "WYB_sendorders_modify",
				"displayName": "修改参保方案",
				"type": 2.0,
				"url": "/jsp/react/sendform/processing/modify",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 352.0,
				"name": "改派服务商",
				"code": "WYB_sendorders_reform",
				"displayName": "改派服务商",
				"type": 2.0,
				"url": "/jsp/react/sendform/sendorders/reform",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 378.0,
				"name": "改派服务商",
				"code": "WYB_processing_reform",
				"displayName": "待处理改派服务商",
				"type": 2.0,
				"url": "/jsp/react/sendform/processing/reform",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 77.0,
				"name": "待反馈",
				"code": "WYB_dfk",
				"displayName": "待反馈单据",
				"type": 1.0,
				"url": "/jsp/sendorders/feedback",
				"relaction_url": "/jsp/sendorders/feedbackdetail,/jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 78.0,
				"name": "已完成",
				"code": "WYB_ywc",
				"displayName": "已完成单据",
				"type": 1.0,
				"url": "/jsp/sendorders/finish",
				"relaction_url": "/jsp/sendorders/finishdetail,jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}, {
				"id": 79.0,
				"name": "失效派单",
				"code": "WYB_sxpd",
				"displayName": "失效派单",
				"type": 1.0,
				"url": "/jsp/sendorders/fail",
				"relaction_url": "/jsp/sendorders/faildetail,jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 75.0
			}]
		}, {
			"id": 395.0,
			"name": "转移服务商",
			"code": "WYB_transferService",
			"displayName": "转移服务商",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 396.0,
				"name": "创建待转移名单",
				"code": "WYB_newTransfer",
				"displayName": "创建待转移名单",
				"type": 2.0,
				"url": "/jsp/react/transferService/newTransfer/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}, {
				"id": 556.0,
				"name": "待转移名单",
				"code": "WYB_waitTransferList",
				"displayName": "待转移名单",
				"type": 1.0,
				"url": "/jsp/react/transferService/waitTransferList/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}, {
				"id": 397.0,
				"name": "转移待减",
				"code": "WYB_waitTransfer",
				"displayName": "转移待减",
				"type": 1.0,
				"url": "/jsp/react/transferService/waitTransfer/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}, {
				"id": 557.0,
				"name": "待转移名单详情",
				"code": "WYB_waitTransferListDetail",
				"displayName": "待转移名单详情",
				"type": 2.0,
				"url": "/jsp/react/transferService/waitTransferListDetail/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}, {
				"id": 398.0,
				"name": "转移待增",
				"code": "WYB_transfering",
				"displayName": "转移待增",
				"type": 1.0,
				"url": "/jsp/react/transferService/transfering/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}, {
				"id": 399.0,
				"name": "所有转移记录",
				"code": "WYB_transferRecord",
				"displayName": "所有转移记录",
				"type": 1.0,
				"url": "/jsp/react/transferService/transferRecord/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 395.0
			}]
		}, {
			"id": 460.0,
			"name": "服务商请款管理",
			"code": "WYB_serviceRequestManage",
			"displayName": "服务商请款管理",
			"type": 1.0,
			"url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb/",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 461.0,
				"name": "发起请款",
				"code": "WYB_myServiceRequest_sponsor",
				"displayName": "发起请款",
				"type": 2.0,
				"url": "/jsp/react/serviceRequestManage/myServiceRequest/sponsor",
				"relaction_url": " ",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 462.0,
				"name": "我的请款",
				"code": "WYB_myServiceRequest",
				"displayName": "我的请款",
				"type": 1.0,
				"url": "/jsp/react/serviceRequestManage/myServiceRequest/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 473.0,
				"name": "我审批的请款",
				"code": "WYB_approvePayment",
				"displayName": "我审批的请款",
				"type": 1.0,
				"url": "/jsp/react/serviceRequestManage/approvePayment/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 477.0,
				"name": "所有服务商请款",
				"code": "WYB_allServiceRequest",
				"displayName": "所有服务商请款",
				"type": 1.0,
				"url": "/jsp/react/serviceRequestManage/allServiceRequest/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 463.0,
				"name": "流程设置",
				"code": "WYB_flowSet",
				"displayName": "流程设置",
				"type": 1.0,
				"url": "/jsp/react/serviceRequestManage/flowSet/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 478.0,
				"name": "服务商请款详情",
				"code": "WYB_allServiceRequest_detail",
				"displayName": "服务商请款详情",
				"type": 2.0,
				"url": "/jsp/react/serviceRequestManage/allServiceRequest/detail",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 460.0
			}, {
				"id": 501.0,
				"name": "服务商付款单导出",
				"code": "WYB_company_payment_export",
				"displayName": "服务商付款单导出",
				"type": 2.0,
				"url": "",
				"system_url": "",
				"system_code": "WYB",
				"parentId": 460.0
			}]
		}, {
			"id": 218.0,
			"name": "参保人余额管理",
			"code": "WYB_insurer_balance",
			"displayName": "参保人余额管理",
			"type": 1.0,
			"url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 219.0,
				"name": "补差待确认",
				"code": "WYB_balance_confirm",
				"displayName": "补差待确认",
				"type": 1.0,
				"url": "/jsp/balance/waitconfirme",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 218.0
			}, {
				"id": 220.0,
				"name": "差额待到账",
				"code": "WYB_arrival_amt",
				"displayName": "差额待到账",
				"type": 1.0,
				"url": "/jsp/balance/waitbill",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 218.0
			}, {
				"id": 221.0,
				"name": "余额待解冻",
				"code": "WYB_balance_thaw",
				"displayName": "余额待解冻",
				"type": 1.0,
				"url": "/jsp/balance/waitthaw",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 218.0
			}, {
				"id": 222.0,
				"name": "余额抵用审核",
				"code": "WYB_balance_verify",
				"displayName": "余额抵用审核",
				"type": 1.0,
				"url": "/jsp/balance/arrivalaudit",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 218.0
			}, {
				"id": 223.0,
				"name": "所有参保人余额",
				"code": "WYB_all_insurer_banlance",
				"displayName": "所有参保人余额",
				"type": 1.0,
				"url": "/jsp/balance/allbalance",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 218.0
			}, {
				"id": 502.0,
				"name": "所有参保人余额解冻退款权限",
				"code": "WYB_all_insurer_banlance_otherrefund",
				"displayName": "所有参保人余额解冻退款权限",
				"type": 2.0,
				"url": " ",
				"system_code": "WYB",
				"parentId": 218.0
			}]
		}, {
			"id": 85.0,
			"name": "财务服务",
			"code": "WYB_finance",
			"displayName": "财务服务",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 469.0,
				"name": "出纳服务商付款",
				"code": "WYB_cashierSerPayment",
				"displayName": "出纳服务商付款",
				"type": 1.0,
				"url": "/jsp/react/finance/cashierSerPayment/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 86.0,
				"name": "出纳客户退款付款",
				"code": "WYB_request",
				"displayName": "出纳客户退款付款",
				"type": 1.0,
				"url": "/jsp/request/requestlist",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 350.0,
				"name": "应收会计",
				"code": "WYB_accountant",
				"displayName": "应收会计",
				"type": 1.0,
				"url": "/jsp/react/finance/accountant/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 536.0,
				"name": "服务商应付会计",
				"code": "WYB_serverDealAccount",
				"displayName": "服务商应付会计",
				"type": 1.0,
				"url": "/jsp/react/finance/serverDealAccount/index",
				"system_url": "http://tigert.joyomm.com/admin/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 470.0,
				"name": "客户退款应付会计",
				"code": "WYB_dealAccount",
				"displayName": "客户退款应付会计",
				"type": 1.0,
				"url": "/jsp/react/finance/dealAccount/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 573.0,
				"name": "服务商发票管理",
				"code": "WYB_supInvoiceManage",
				"displayName": "服务商发票管理",
				"type": 1.0,
				"url": "/jsp/react/finance/supInvoiceManage/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 471.0,
				"name": "余额对账",
				"code": "WYB_balanceRecon",
				"displayName": "余额对账",
				"type": 1.0,
				"url": "/jsp/react/finance/balanceRecon/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 468.0,
				"name": "付款账号设置",
				"code": "WYB_paymentAccountSet",
				"displayName": "付款账号设置",
				"type": 1.0,
				"url": "/jsp/react/finance/paymentAccountSet/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 430.0,
				"name": "到款明细导出",
				"code": "WYB_accountant_receive_export",
				"displayName": "到款明细导出",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 431.0,
				"name": "账单明细导出",
				"code": "WYB_accountant_bill_export",
				"displayName": "账单明细导出",
				"type": 2.0,
				"url": "",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 472.0,
				"name": "参保人保费出入账报表",
				"code": "WYB_accountInsured",
				"displayName": "参保人保费出入账报表",
				"type": 2.0,
				"url": "/jsp/react/finance/accountInsured/index",
				"system_url": "http://tigert.joyomm.com/joyowyb/",
				"system_code": "WYB",
				"parentId": 85.0
			}, {
				"id": 537.0,
				"name": "批量确认付款",
				"code": "WYB_batchConfirm",
				"displayName": "批量确认付款",
				"type": 2.0,
				"url": "/jsp/react/finance/batchConfirm/index",
				"system_url": "http://tigert.joyomm.com/admin/",
				"system_code": "WYB",
				"parentId": 85.0
			}]
		}, {
			"id": 82.0,
			"name": "客户服务",
			"code": "WYB_cus",
			"displayName": "客户服务",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 84.0,
				"name": "特殊审批",
				"code": "WYB_approve",
				"displayName": "特殊审批",
				"type": 1.0,
				"url": "/jsp/special/speciallist",
				"relaction_url": "/jsp/special/spedetail,/jsp/order/orderoverdetail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 82.0
			}, {
				"id": 27.0,
				"name": "用户反馈",
				"code": "feedbackmanage",
				"displayName": "用户反馈",
				"type": 1.0,
				"url": "/usermanage/usermanage/feedbackmanage",
				"relaction_url": "/usermanage/usermanage/feedbackdetail",
				"system_url": "",
				"system_code": "PHPADMIN",
				"parentId": 82.0
			}]
		}, {
			"id": 149.0,
			"name": "代理商管理",
			"code": "WYB_agent",
			"displayName": "代理商管理",
			"type": 1.0,
			"url": "",
			"system_url": "http://tigert.joyomm.com/joyowyb",
			"system_code": "WYB",
			"parentId": 26.0,
			"children": [{
				"id": 147.0,
				"name": "城市等级设置",
				"code": "WYB_citylevel",
				"displayName": "城市等级设置",
				"type": 1.0,
				"url": "/jsp/citygrade/gradelist",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 149.0
			}, {
				"id": 146.0,
				"name": "城市代管理",
				"code": "WYB_agentcity",
				"displayName": "城市代管理",
				"type": 1.0,
				"url": "/jsp/cityagent/list",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 149.0
			}, {
				"id": 204.0,
				"name": "业绩管理",
				"code": "WYB_achievementmanage",
				"displayName": "业绩管理",
				"type": 1.0,
				"url": "/jsp/cityagent/achievementmanage",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 149.0
			}]
		}, {
			"id": 400.0,
			"name": "销售管理",
			"code": "cms",
			"displayName": "销售管理",
			"type": 1.0,
			"system_url": "http://wybcrm.joyomm.com",
			"system_code": "WYBCRM",
			"parentId": 26.0,
			"children": [{
				"id": 401.0,
				"name": "我的线索",
				"code": "CMS_clue",
				"displayName": "我的线索",
				"type": 1.0,
				"url": "/cms/clue/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 402.0,
				"name": "我的线索-新增",
				"code": "CMS_clue_create",
				"displayName": "我的线索-新增",
				"type": 2.0,
				"url": "/cms/clue/create",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 403.0,
				"name": "我的线索-导入",
				"code": "CMS_clue_lead",
				"displayName": "我的线索-导入",
				"type": 2.0,
				"url": "/cms/clue/lead",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 404.0,
				"name": "我的业绩",
				"code": "CMS_myPerformance",
				"displayName": "我的业绩",
				"type": 1.0,
				"url": "/cms/myPerformance/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 405.0,
				"name": "设置提成规则",
				"code": "CMS_setCommissionRule",
				"displayName": "设置提成规则",
				"type": 1.0,
				"url": "/cms/setCommissionRule/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 406.0,
				"name": "成交客户",
				"code": "CMS_myClient",
				"displayName": "成交客户",
				"type": 1.0,
				"url": "/cms/myClient/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 407.0,
				"name": "所有业绩",
				"code": "CMS_allPerformance",
				"displayName": "所有业绩",
				"type": 1.0,
				"url": "/cms/allPerformance/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 408.0,
				"name": "线索总池",
				"code": "CMS_totalPool",
				"displayName": "线索总池",
				"type": 1.0,
				"url": "/cms/totalPool/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 409.0,
				"name": "设置分配规则",
				"code": "CMS_setAllocationRule",
				"displayName": "设置分配规则",
				"type": 1.0,
				"url": "/cms/setAllocationRule/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 410.0,
				"name": "查看线索客户",
				"code": "CMS_viewLeadClient",
				"displayName": "查看线索客户",
				"type": 2.0,
				"url": "/cms/viewLeadClient/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 411.0,
				"name": "查看成交客户",
				"code": "CMS_viewSuccessClient",
				"displayName": "查看成交客户",
				"type": 2.0,
				"url": "/cms/viewSuccessClient/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 418.0,
				"name": "调整所属销售",
				"code": "CMS_adjust_cousultants",
				"displayName": "调整所属销售",
				"type": 2.0,
				"url": "",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 419.0,
				"name": "调整业绩",
				"code": "CMS_adjust_commission",
				"displayName": "调整业绩",
				"type": 2.0,
				"url": "",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 424.0,
				"name": "业绩汇总",
				"code": "CMS_performanceSummary",
				"displayName": "业绩汇总",
				"type": 1.0,
				"url": "/cms/performanceSummary/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 425.0,
				"name": "查看业绩详情",
				"code": "CMS_viewPerformanceDetail",
				"displayName": "查看业绩详情",
				"type": 2.0,
				"url": "/cms/viewPerformanceDetail/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}, {
				"id": 458.0,
				"name": "所有客户",
				"code": "CMS_allClient",
				"displayName": "所有客户",
				"type": 1.0,
				"url": "/cms/allClient/index",
				"system_url": "http://wybcrm.joyomm.com",
				"system_code": "WYBCRM",
				"parentId": 400.0
			}]
		}, {
			"id": 8.0,
			"name": "代金券管理",
			"code": "WYB_voucherManage",
			"displayName": "代金券管理",
			"type": 1.0,
			"url": "",
			"relaction_url": "",
			"system_url": "",
			"system_code": "PHPADMIN",
			"parentId": 26.0,
			"children": [{
				"id": 394.0,
				"name": "充值发券",
				"code": "WYB_activityList_send",
				"displayName": "充值发券",
				"type": 2.0,
				"url": "/jsp/react/voucherManage/activityList/send",
				"relaction_url": "",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 8.0
			}, {
				"id": 423.0,
				"name": "新建活动",
				"code": "WYB_newActivity",
				"displayName": "新建活动",
				"type": 1.0,
				"url": "/jsp/react/voucherManage/newActivity/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 8.0
			}, {
				"id": 447.0,
				"name": "代金券详情",
				"code": "WYB_voucherDetail",
				"displayName": "代金券详情",
				"type": 2.0,
				"url": "/jsp/react/voucherManage/tickActivityManage/detail",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 8.0
			}, {
				"id": 439.0,
				"name": "所有活动券",
				"code": "WYB_allCoupons",
				"displayName": "所有活动券",
				"type": 1.0,
				"url": "/jsp/react/voucherManage/allCoupons/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 8.0
			}, {
				"id": 440.0,
				"name": "券活动管理",
				"code": "WYB_tickActivityManage",
				"displayName": "券活动管理",
				"type": 1.0,
				"url": "/jsp/react/voucherManage/tickActivityManage/index",
				"system_url": "http://tigert.joyomm.com/joyowyb",
				"system_code": "WYB",
				"parentId": 8.0
			}]
		}]
	}]
}

// 代码中会兼容本地 service mock 以及部署站点的静态数据
const proxy = {

  'GET /api/cms/info': (req, res) => {
    res.send(json)
  },


  // 支持值为 Object 和 Array
  'GET /api/currentUser': {
    $desc: '获取当前用户接口',
    $params: {
      pageSize: {
        desc: '分页',
        exp: 2,
      },
    },
    $body: {
      name: 'Serati Ma',
      avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png',
      userid: '00000001',
      notifyCount: 12,
    },
  },
  // GET POST 可省略
  'GET /api/users': [
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York No. 1 Lake Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      address: 'London No. 1 Lake Park',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      address: 'Sidney No. 1 Lake Park',
    },
  ],
  'GET /api/project/notice': getNotice,
  'GET /api/activities': getActivities,
  'GET /api/rule': getRule,
  'POST /api/rule': {
    $params: {
      pageSize: {
        desc: '分页',
        exp: 2,
      },
    },
    $body: postRule,
  },
  'POST /api/forms': (req, res) => {
    res.send({ message: 'Ok' });
  },
  'GET /api/tags': mockjs.mock({
    'list|100': [{ name: '@city', 'value|1-100': 150, 'type|0-2': 1 }],
  }),
  'GET /api/fake_list': getFakeList,
  'GET /api/fake_chart_data': getFakeChartData,
  'GET /api/profile/basic': getProfileBasicData,
  'GET /api/profile/advanced': getProfileAdvancedData,
  'POST /api/login/account': (req, res) => {
    const { password, userName, type } = req.body;
    if (password === '888888' && userName === 'admin') {
      res.send({
        status: 'ok',
        type,
        currentAuthority: 'admin',
      });
      return;
    }
    if (password === '123456' && userName === 'user') {
      res.send({
        status: 'ok',
        type,
        currentAuthority: 'user',
      });
      return;
    }
    res.send({
      status: 'error',
      type,
      currentAuthority: 'guest',
    });
  },
  'POST /api/register': (req, res) => {
    res.send({ status: 'ok', currentAuthority: 'user' });
  },
  'GET /api/notices': getNotices,
  'GET /api/500': (req, res) => {
    res.status(500).send({
      timestamp: 1513932555104,
      status: 500,
      error: 'error',
      message: 'error',
      path: '/base/category/list',
    });
  },
  'GET /api/404': (req, res) => {
    res.status(404).send({
      timestamp: 1513932643431,
      status: 404,
      error: 'Not Found',
      message: 'No message available',
      path: '/base/category/list/2121212',
    });
  },
  'GET /api/403': (req, res) => {
    res.status(403).send({
      timestamp: 1513932555104,
      status: 403,
      error: 'Unauthorized',
      message: 'Unauthorized',
      path: '/base/category/list',
    });
  },
  'GET /api/401': (req, res) => {
    res.status(401).send({
      timestamp: 1513932555104,
      status: 401,
      error: 'Unauthorized',
      message: 'Unauthorized',
      path: '/base/category/list',
    });
  },
};

export default (noProxy ? {} : delay(proxy, 1000));
